services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lab3db-back
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app:Z
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/db?schema=public"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lab3db-front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app:Z
      - /usr/src/app/node_modules

  db:
    image: postgres:17
    container_name: lab3db-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
